customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('',views.index, name="index"),
    path('kitchens/', views.kitchens, name="kitchens"),
    path('kitchens/<int:kid>', views.kitchen, name="kitchen"),
    path('kitchens/<int:kid>/<int:tid>', views.tiffin, name="tiffin")
]

tiffin50/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vendor/',include('vendor.urls')),
    path('', include('customer.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneNum = models.CharField(max_length=10)

    def __str__(self):
        return self.user.get_full_name()


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)



class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null = True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total



class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null = True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

customer/views.py
from django.shortcuts import render, redirect
from vendor.models import Kitchen, Tiffin


def index(request):
    return redirect("kitchens/")


def kitchens(request):
    kitchensList = Kitchen.objects.all()
    context = {'kitchens': kitchensList}
    return render(request, "kitchens.html", context)


def kitchen(request, kid):
    try:
        kitchenObj = Kitchen.objects.get(id=kid)

    except:
        return redirect('/')

    tiffinList = Tiffin.objects.filter(kitchen=kitchenObj)

    context = {'tiffins': tiffinList, 'kitchen': kitchenObj}

    return render(request, "tiffins.html", context)


def tiffin(request, kid, tid):
    try:
        kitchenObj = Kitchen.objects.get(id=kid)
        tiffinObj = Tiffin.objects.get(id=tid)

    except:
        return redirect('/')

    context = {'tiffin': tiffinObj, 'kitchen': kitchenObj}

    return render(request, "test.html", context)

customer/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <title>Tiffin50</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'customer/custom.css' %}">
</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="navbar-toggler-icon"></span>
        </button> <a class="navbar-brand" href="#">Brand</a>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="navbar-nav">
                <li class="nav-item active">
                     <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                         <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider">
                        </div> <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="text" />
                <button class="btn btn-primary my-2 my-sm-0" type="submit">
                    Search
                </button>
            </form>
            <ul class="navbar-nav ml-md-auto">
                <li class="nav-item active">
                     <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                         <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider">
                        </div> <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

        {% block content %}
        {% endblock content %}
    <div class="row">
		<div class="col-md-4">

			<address>
				 <strong>Twitter, Inc.</strong><br /> 795 Folsom Ave, Suite 600<br /> San Francisco, CA 94107<br /> <abbr title="Phone">P:</abbr> (123) 456-7890
			</address>
		</div>
		<div class="col-md-4">
			<blockquote class="blockquote">
				<p class="mb-0">
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
				</p>
				<footer class="blockquote-footer">
					Someone famous in <cite>Source Title</cite>
				</footer>
			</blockquote>
		</div>
		<div class="col-md-4">

			<address>
				 <strong>Twitter, Inc.</strong><br /> 795 Folsom Ave, Suite 600<br /> San Francisco, CA 94107<br /> <abbr title="Phone">P:</abbr> (123) 456-7890
			</address>
		</div>
	</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'customer/custom.js' %}"></script>
  </body>
</html>

customer/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


	<div class="row">
		<div class="col-md-12">

			<div class="carousel slide" id="carousel-274460">
				<ol class="carousel-indicators">
					<li data-slide-to="0" data-target="#carousel-274460">
					</li>
					<li data-slide-to="1" data-target="#carousel-274460">
					</li>
					<li data-slide-to="2" data-target="#carousel-274460" class="active">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="carousel-item">
						<img class="d-block w-100" alt="Carousel Bootstrap First" src="https://www.layoutit.com/img/sports-q-c-1600-500-1.jpg" />
						<div class="carousel-caption">
							<h4>
								First Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
					<div class="carousel-item">
						<img class="d-block w-100" alt="Carousel Bootstrap Second" src="https://www.layoutit.com/img/sports-q-c-1600-500-2.jpg" />
						<div class="carousel-caption">
							<h4>
								Second Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
					<div class="carousel-item active">
						<img class="d-block w-100" alt="Carousel Bootstrap Third" src="https://www.layoutit.com/img/sports-q-c-1600-500-3.jpg" />
						<div class="carousel-caption">
							<h4>
								Third Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
				</div> <a class="carousel-control-prev" href="#carousel-274460" data-slide="prev"><span class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a class="carousel-control-next" href="#carousel-274460" data-slide="next"><span class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
			</div>
		</div>
	</div>
    <br><br>
	<div class="row border border-info">
		<div class="col-md-2">
			<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg" class="img-thumbnail" />
		</div>
		<div class="col-md-10">
			<h3>
				h3. Lorem ipsum dolor sit amet.
			</h3>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<div class="row">
				<div class="col-md-4">
					 <a href="#" class="btn btn-md btn-success" type="button">BreakFast</a>
				</div>
				<div class="col-md-4">
					 <a href="#" class="btn btn-success" type="button">lunch</a>
				</div>
				<div class="col-md-4">
					 <a href="#" class="btn btn-success" type="button">Dinner</a>
				</div>
			</div>
		</div>
	</div>
    <br>
	<div class="row border border-info">
		<div class="col-md-2">
			<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg" class="img-thumbnail" />
		</div>
		<div class="col-md-10">
			<h3>
				h3. Lorem ipsum dolor sit amet.
			</h3>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<div class="row">
				<div class="col-md-4">
					 <a href="#" class="btn btn-md btn-success" type="button">Button</a>
				</div>
				<div class="col-md-4">
					 <a href="#" class="btn btn-success" type="button">Button</a>
				</div>
				<div class="col-md-4">
					 <a href="#" class="btn btn-success" type="button">Button</a>
				</div>
			</div>
		</div>
	</div>
    <br>
	<div class="row border border-info">
		<div class="col-md-2">
			<img alt="Bootstrap Image Preview" src="https://www.layoutit.com/img/sports-q-c-140-140-3.jpg" class="img-thumbnail" />
		</div>
		<div class="col-md-10">
			<h3>
				h3. Lorem ipsum dolor sit amet.
			</h3>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<div class="row">
				<div class="col-md-4">
					 <a href="#" class="btn btn-md btn-success" type="button">Button</a>
				</div>
				<div class="col-md-4">
					 <a href="#" class="btn btn-success" type="button">Button</a>
				</div>
				<div class="col-md-4">
					 <a href="#" class="btn btn-success" type="button">Button</a>
				</div>
			</div>
		</div>


	</div>
     <br><br>
	<div class="row">
		<div class="col-md-12">
			<nav>
				<ul class="pagination">
					<li class="page-item">
						<a class="page-link" href="#">Previous</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">1</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">2</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">3</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">4</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">5</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">Next</a>
					</li>
				</ul>
			</nav>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">

			<address>
				 <strong>Twitter, Inc.</strong><br /> 795 Folsom Ave, Suite 600<br /> San Francisco, CA 94107<br /> <abbr title="Phone">P:</abbr> (123) 456-7890
			</address>
		</div>
		<div class="col-md-4">
			<blockquote class="blockquote">
				<p class="mb-0">
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
				</p>
				<footer class="blockquote-footer">
					Someone famous in <cite>Source Title</cite>
				</footer>
			</blockquote>
		</div>
		<div class="col-md-4">

			<address>
				 <strong>Twitter, Inc.</strong><br /> 795 Folsom Ave, Suite 600<br /> San Francisco, CA 94107<br /> <abbr title="Phone">P:</abbr> (123) 456-7890
			</address>
		</div>
	</div>



{% endblock content %}

customer/templates/kitchens.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Best Kitchens</h1>
          <p class="lead text-muted">Hungry? Just order some delicious food from the best kitchens in your area..!! beat the hunger with us !!</p>
          <p>
            <a href="{%url 'customer:kitchens' %}" class="btn btn-primary my-2">Kitchens</a>
            <a href="#" class="btn btn-secondary my-2">Tiffins</a>
          </p>
        </div>
      </section>
      {% for kitchen in kitchens %}
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{kitchen.photo1.url}}" data-holder-rendered="true">
                <div class="card-body">
                    <p class="card-text"><strong>{{kitchen.name}}</strong> <br> <i>{{kitchen.address}}</i></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">BreakFast</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Lunch</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Dinner</button>
                        </div>
                        <small class="text-muted">RATINGS: {{kitchen.rating}}</small>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </main>

{% endblock content %}

customer/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>

</body>
</html>

customer/templates/tiffins.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Best Kitchens</h1>
          <p class="lead text-muted">Hungry? Just order some delicious food from the best kitchens in your area..!! beat the hunger with us !!</p>
          <p>
            <a href="{%url 'customer:kitchens' %}" class="btn btn-primary my-2">Kitchens</a>
            <a href="#" class="btn btn-secondary my-2">Tiffins</a>
          </p>
        </div>
      </section>
      {% for tiffin in tiffins %}
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{tiffin.photo1.url}}" data-holder-rendered="true">
                <div class="card-body">
                    <p class="card-text"><strong>{{tiffin.name}}</strong><br> by <br> <i>{{tiffin.kitchen.name}}</i></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">BreakFast</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Lunch</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Dinner</button>
                        </div>
                        <small class="text-muted">Type: {{tiffin.tiffinType}}</small>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </main>

{% endblock content %}